---
title: "Questionnaires and Factor analysis"
author: "Ondrej Zika and Sam Hall-McMaster"
output:
  html_document:
    df_print: paged
---


```{r}
library(here)
here::i_am(".ed-foraging-root")
#renv::restore(here::here())


renv::load(here::here())
 
# data set 
# "" = stadnard EAT26<14
# "_alt_cutoff" = alternative cutoff EAT26<20
data_set = "_alt_cutoff"

questionnaire_family = "with_cia" # alt without cia - for the review process, asked by the reviewers

corr_type = "spearman"

required_packages = c("glmmTMB", "car", "parameters","tidyr", "see", "dplyr", "lmerTest", "parameters", "emmeans", "modelbased", "ggpubr", "kableExtra", "psych", "GPArotation", "corrplot", "nFactors")
invisible(lapply(required_packages, require, character.only = TRUE))

adjustment_method = "holm"
```
```{r}
data <- read.csv(here::here( 'anon-data', 'task_data', paste0('full_beh_data',data_set,'.csv')))
data$logRT <- log(data$RT)
data$log_patch_actions_taken <- log(data$patch_actions_taken)
data <- data %>%
  mutate(decision_type = recode(decision_type, `1` = 0, `2` = 1))

## add questionnaires data 
qs <- read.csv(here::here( 'anon-data', 'questionnaires', paste0('anonymized_processed_questonnaire_data',data_set,'.csv')))
qs$id <- qs$PROLIFICID
if (questionnaire_family=="with_cia") {
  qs <- qs[,c("id", "bmi",  "eat26",  "eat26_oralcontrol", "eat26_dieting", "eat26_bulimia",  "edeq",  "aai", "stait", "bdi",  "iou", "cia",   "oci")]
}  else if (questionnaire_family=="without_cia") {
  qs <- qs[,c("id", "bmi",  "eat26",  "eat26_oralcontrol", "eat26_dieting", "eat26_bulimia",  "edeq",  "aai", "stait", "bdi",  "iou", "oci")]
}
data = merge(data, qs, by=c("id")) # NA's match



fa.scores <- read.csv(here::here( 'anon-data', 'questionnaires', paste0('factor_scores',data_set,'.csv')))
data = merge(data, fa.scores, by=c("id")) # NA's match

# extract questionnaires by group 
if (questionnaire_family=="with_cia") {
  vars2summarize <- c("age", "bmi", "EducationYears", "eat26",  "eat26_oralcontrol", "eat26_dieting", "eat26_bulimia",  "edeq",  "aai", "stait", "bdi",  "iou", "cia",  "oci", "F1", "F2", "F3")
}  else if (questionnaire_family=="without_cia") {
  vars2summarize <- c("age", "bmi", "EducationYears", "eat26",  "eat26_oralcontrol", "eat26_dieting", "eat26_bulimia",  "edeq",  "aai", "stait", "bdi",  "iou", "oci", "F1", "F2", "F3")
}
df <- data %>%   group_by(id, group) %>%
  summarise_at(vars2summarize, mean, na.rm = TRUE)

write.csv(df, here::here("output", paste0("basic_demographics",data_set,".csv")))
```
## Func

```{r}
run_descriptives <- function(df, vec) {
  sdf <- df[, append("group", vec)]
  
  # Calculate means
  group_means <- sdf %>%
    group_by(group) %>%
    summarise(across(all_of(vec), mean, na.rm = TRUE)) %>%
    pivot_longer(-group, names_to = "variable", values_to = "mean")
  
  # Calculate standard deviations
  group_sds <- sdf %>%
    group_by(group) %>%
    summarise(across(all_of(vec), sd, na.rm = TRUE)) %>%
    pivot_longer(-group, names_to = "variable", values_to = "sd")
  
  # Calculate p-values, t-scores, and degrees of freedom
  pvals <- sdf %>%
    summarise(across(all_of(vec), ~t.test(.[group == "group1"], .[group == "group2"])$p.value))
  tscores <- sdf %>%
    summarise(across(all_of(vec), ~t.test(.[group == "group1"], .[group == "group2"])$statistic))
  dfs <- sdf %>%
    summarise(across(all_of(vec), ~t.test(.[group == "group1"], .[group == "group2"])$parameter))
  
  # Combine p-values, t-scores, and degrees of freedom into a single data frame
  stats <- rbind(pvals, tscores, dfs)
  stats <- data.table::transpose(stats)
  colnames(stats) <- c("p", "t", "df")
  stats$variable <- vec
  
  # Reshape group means and standard deviations
  group_means <- group_means %>%
    pivot_wider(names_from = group, values_from = mean, names_prefix = "mean_")
  
  group_sds <- group_sds %>%
    pivot_wider(names_from = group, values_from = sd, names_prefix = "sd_")
  
  # Merge all statistics into a final data frame
  final_stats <- merge(stats, group_means, by = "variable")
  final_stats <- merge(final_stats, group_sds, by = "variable")

  return(final_stats)
}


```
```{r}

```

## Group means
```{r}

df2 <- df %>%   group_by(group) %>%
  summarise_at(vars2summarize, mean, na.rm = TRUE)
df2
write.csv(df2, here::here("output", paste0("basic_demographics_group_means",data_set,".csv")))
```

```{r}

df2 <- data %>%
  group_by(id, group) %>%
  summarise(
    gender = mean(gender, na.rm = TRUE)
  )


result <- df2 %>%
  group_by(gender, group) %>%
  count() %>%
  ungroup()

print(result)
data_matrix <- matrix(c(40, 45, 4, 1), nrow = 2, byrow = FALSE)
data_matrix
chisq.test(data_matrix)

fisher.test(data_matrix)

```

## Group tests
```{r}
stats <- run_descriptives(df, vars2summarize)
stats$p <- round(as.numeric(stats$p), 4)
stats$t <- round(as.numeric(stats$t), 3)
stats$mean_group1 <- round(as.numeric(stats$mean_group1), 2)
stats$mean_group2 <- round(as.numeric(stats$mean_group2), 2)
stats$sd_group1 <- round(as.numeric(stats$sd_group1), 2)
stats$sd_group2 <- round(as.numeric(stats$sd_group2), 2)
stats$df <- round(as.numeric(stats$df), 2)
stats <- stats[,c("variable","mean_group1", "sd_group1","mean_group2", "sd_group2", "t", "df", "p")]

# Create a publication-ready table
tb <- kable(stats, caption = "Table 1") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, bold = FALSE) %>%
  #column_spec(2, bold = FALSE, color = "black") %>%
  add_header_above(c(" " = 1, "Group 1" = 2, "Group 2" = 2, " "=3)) %>%
  save_kable(here::here("output", "table1.png"))
write.csv(stats, here::here("output", paste0("table1",data_set,".csv")))
print(stats)
# selected 
stats2<-stats[stats$variable %in% c("age", "bdi", "F1", "F2", "F3"),]
write.csv(stats2, here::here("output", "table1_reduced.csv"))
tb <- kable(stats2, caption = "Table 1") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, bold = FALSE) %>%
  #column_spec(2, bold = FALSE, color = "black") %>%
  add_header_above(c(" " = 2, "Group 1" = 2, "Group 2" = 2, " "=3)) %>%
  save_kable(here::here("output", paste0("table1_reduced",data_set,".png")))

```

#lot 
```{r}
df_long <- data %>%
  group_by(id, group) %>%
  summarise_at(c("F1", "F2", "F3"), mean, na.rm = TRUE) %>%
  select(F1, F2, F3, group) %>%
  pivot_longer(cols = c(F1, F2, F3), names_to = "Variable", values_to = "Value")

df_summary <- df_long %>%
  group_by(group, Variable) %>%
  summarise(
    mean_value = mean(Value),
    se_value = sd(Value) / sqrt(n())
  )

# Create the bar plot with error bars
ggplot(df_summary, aes(x = Variable, y = mean_value, fill = group)) +
  geom_bar(stat = "identity", position = position_dodge(), color = "black") +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value), 
                position = position_dodge(0.9), width = 0.25) +
  theme_minimal() +
  labs(title = "Bar Plot of F1, F2, and F3 by Group",
       x = "Variable",
       y = "Mean Value",
       fill = "Group") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
### Factor analysis
```{r fig.width=15, fig.height=15}
qs <- read.csv(here::here( 'anon-data', 'questionnaires', paste0('anonymized_item_questonnaire_data',data_set,'.csv')))

if (questionnaire_family=="with_cia") {
 # qs <- qs[,c("id", "bmi",  "eat26",  "eat26_oralcontrol", "eat26_dieting", "eat26_bulimia",  "edeq",  "aai", "stait", "bdi",  "iou", "cia",   "oci")]
}  else if (questionnaire_family=="without_cia") {
  qs <- qs[,!grepl("cia", colnames(qs))]
  
  #qs <- qs[,c("id", "bmi",  "eat26",  "eat26_oralcontrol", "eat26_dieting", "eat26_bulimia",  "edeq",  "aai", "stait", "bdi",  "iou", "oci")]
}


cdf <- cor(qs[, !(colnames(qs) %in% c("X", "PROLIFICID"))], method=corr_type)
corrplot::corrplot(cdf)
```

```{r fig.width=15}
#res = parameters::n_factors(qs[, !(colnames(qs) %in% c("X", "PROLIFICID"))], type="FA", rotation="oblimin")
#see::plots(res)
#print(res)
evals <- eigen(cdf)$values 
psych::scree(cdf, factors = TRUE)
```
#CNG
```{r}
tt <- qs[, !(colnames(qs) %in% c("X", "PROLIFICID"))]
m <- nFactors::nCng(data.frame(tt), cor = TRUE, model = "factors", details = TRUE)
print(m)
m$detail
plotuScree(data.frame(tt), main=paste(m$nFactors,
                          " factors retained by the CNG procedure",
                          sep=""))
```

```{r}
library(tidyr)
fa3 <- fa(as.matrix(cdf), nfactors = 3, rotate = "oblimin", fm = "minres", scores = "Bartlett")

fa3.load <- data.frame(unclass(fa3$loadings))


if (questionnaire_family=="with_cia") {
questionnaire_info <- data.frame(
  item = colnames(cdf),
   questionnaire = c(rep("EAT-26 (Eating Attitudes)", 26), rep("EDE-Q (Eating Disorder)", 22), rep("CIA (Clinical Impairment)", 16), rep("AAI (Appearance Anxiety)", 10), 
                    rep("STAI-T (Trait Anxiety)", 20), rep("BDI (Depression)", 21), 
                    rep("IOU (Intolerance of Uncertainty)", 21), rep("OCI (Obsessive-Compulsive Inventory)", 18))  # Adjust this based on your actual data
)

}  else if (questionnaire_family=="without_cia") {
     questionnaire_info <- data.frame(
  item = colnames(cdf),
   questionnaire = c(rep("EAT-26 (Eating Attitudes)", 26), rep("EDE-Q (Eating Disorder)", 22),  rep("AAI (Appearance Anxiety)", 10), 
                    rep("STAI-T (Trait Anxiety)", 20), rep("BDI (Depression)", 21), 
                    rep("IOU (Intolerance of Uncertainty)", 21), rep("OCI (Obsessive-Compulsive Inventory)", 18))  # Adjust this based on your actual data
)
   
}


# Melt the data for ggplot
fa3.load$item <- rownames(fa3.load)
fa3.load <- fa3.load %>% gather(factor, loading, -item)

# Rename factors
fa3.load$factor <- recode(fa3.load$factor, 
                          MR1 = "F1: Eating Attitudes", 
                          MR2 = "F2: Uncertainty Sensitivity", 
                          MR3 = "F3: Anxiety & Depression")

# Merge with questionnaire info
plot_data <- merge(fa3.load, questionnaire_info, by = "item")
```

```{r fig.width=15, fig.height=7}
# Define colors for each questionnaire
if (questionnaire_family=="with_cia") {
   questionnaire_colors <- c("EAT-26 (Eating Attitudes)" = "purple", "EDE-Q (Eating Disorder)" = "deeppink", "CIA (Clinical Impairment)" = "yellow3", "AAI (Appearance Anxiety)" = "brown2", 
                          "STAI-T (Trait Anxiety)" = "midnightblue", "BDI (Depression)" = "dodgerblue", 
                          "IOU (Intolerance of Uncertainty)" = "darkgoldenrod2", "OCI (Obsessive-Compulsive Inventory)" = "seagreen4")
  }  else if (questionnaire_family=="without_cia") {
    questionnaire_colors <- c("EAT-26 (Eating Attitudes)" = "purple", "EDE-Q (Eating Disorder)" = "deeppink", "AAI (Appearance Anxiety)" = "brown2", 
                          "STAI-T (Trait Anxiety)" = "midnightblue", "BDI (Depression)" = "dodgerblue", 
                          "IOU (Intolerance of Uncertainty)" = "darkgoldenrod2", "OCI (Obsessive-Compulsive Inventory)" = "seagreen4")
  }



# Plot factor loadings
plot_factor_loadings <- ggplot(plot_data, aes(x = item, y = loading, fill = questionnaire)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0, color = "black") +  # Add y=0 line
  facet_wrap(~ factor, scales = "free_x", ncol = 1) +
  scale_fill_manual(values = questionnaire_colors) +
  theme(axis.text.x = element_blank(),  # Remove x tick labels
        axis.ticks.x = element_blank(),  # Remove x tick marks
        strip.background = element_blank(),  # Remove background from strip
        strip.text = element_text(size = 14, face = "plain", hjust = 0),  # Move title to the left and increase font size
        panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank(),  # Remove minor grid lines
        panel.background = element_blank(),  # Remove panel background
        axis.line.x = element_blank(),  # Remove x axis line
        axis.line.y = element_blank(),  # Remove y axis line
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10)) +
  labs(x = "Individual items", y = "Loading",fill = "")



# Print the plot
print(plot_factor_loadings)

ggsave(
  here::here("output", "fa.pdf"), 
  scale = 1,
  width = 15,
  height = 7,
  units = c("in"),
  dpi = 300)

```

```{r}

# Plot factor loadings
plot_factor_loadings <- ggplot(plot_data, aes(x = item, y = loading, fill = questionnaire)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ factor, scales = "free_x") +
  scale_fill_manual(values = questionnaire_colors) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "Individual questionnaire items", y = "Respective loadings for each factor")

# Prepare the correlation matrix
cor_matrix <- cor(cdf)

# Plot the correlation matrix
plot_correlation_matrix <- corrplot(cor_matrix, method = "color", tl.cex = 0.6)


```

```{r}
ddf <- qs[, !(colnames(qs) %in% c("X", "PROLIFICID"))]
scores <- data.frame(cbind(qs[,"PROLIFICID"], factor.scores(ddf, fa3, method = "Thurstone")$scores))
scores[,2:4] <- data.frame(lapply(scores[,2:4], as.numeric))
colnames(scores) <- c("id", "F1", "F2", "F3")
write.csv(scores, here::here( 'anon-data', 'questionnaires', paste0('factor_scores',data_set,'.csv')))
```


### Correlate all Items

```{r}
dfs = read.csv(here::here("anon-data", "task_data", "speeding_up_effect.csv"))
dfs$id <- as.factor(dfs$id)
dfs$remaining_time <- as.numeric(dfs$remaining_time)
dfs <- dfs[,c("id", "remaining_time")]

## add questionnaires data 
qs <- read.csv(here::here( 'anon-data', 'questionnaires', paste0('anonymized_item_questonnaire_data',data_set,'.csv')))
qs$id <- as.factor(qs$PROLIFICID)


dfs2 = merge(dfs, qs, on="id", all.y = TRUE)

dfs2<-dfs2[,colnames(dfs2)[!grepl("id", colnames(dfs2)) & !grepl("PROLIFICID", colnames(dfs2)) & !grepl("X", colnames(dfs2))]]


```

```{r fig.width=12, fig.height=4}

cdf <- data.frame(cor(dfs2, method = "spearman")[,c("remaining_time")])
cdf2 <- cdf[!grepl("remaining_time", rownames(cdf)),]


if (questionnaire_family=="with_cia") {
  rtcors <- data.frame(
    item = rownames(cdf)[2:155],
    corr = cdf[!grepl("remaining_time", rownames(cdf)),], 
     questionnaire = c(rep("EAT-26 (Eating Attitudes)", 26), rep("EDE-Q (Eating Disorder)", 22), rep("CIA (Clinical Impairment)", 16), rep("AAI (Appearance Anxiety)", 10), 
                      rep("STAI-T (Trait Anxiety)", 20), rep("BDI (Depression)", 21), 
                      rep("IOU (Intolerance of Uncertainty)", 21), rep("OCI (Obsessive-Compulsive Inventory)", 18))  # Adjust this based on your actual data
  )

}  else if (questionnaire_family=="without_cia") {
     rtcors <- data.frame(
       item = rownames(cdf)[2:155],
    corr = cdf[!grepl("remaining_time", rownames(cdf)),], 
     questionnaire = c(rep("EAT-26 (Eating Attitudes)", 26), rep("EDE-Q (Eating Disorder)", 22),  rep("AAI (Appearance Anxiety)", 10), 
                      rep("STAI-T (Trait Anxiety)", 20), rep("BDI (Depression)", 21), 
                      rep("IOU (Intolerance of Uncertainty)", 21), rep("OCI (Obsessive-Compulsive Inventory)", 18))  # Adjust this based on your actual data
  )
   
}

names <- read.csv(here::here('anon-data', 'questionnaires', 'single_item_names.csv'))
write.csv(rtcors, here::here('anon-data', 'task_data', 'correlations_with_items.csv'))

rtcors = merge(rtcors, names, at=item)
rtcors <- rtcors %>%
  arrange(desc(corr)) %>%
  mutate(full_question = factor(full_question, levels = unique(full_question)))


if (questionnaire_family=="with_cia") {
   questionnaire_colors <- c("EAT-26 (Eating Attitudes)" = "purple", "EDE-Q (Eating Disorder)" = "deeppink", "CIA (Clinical Impairment)" = "yellow3", "AAI (Appearance Anxiety)" = "brown2", 
                          "STAI-T (Trait Anxiety)" = "midnightblue", "BDI (Depression)" = "dodgerblue", 
                          "IOU (Intolerance of Uncertainty)" = "darkgoldenrod2", "OCI (Obsessive-Compulsive Inventory)" = "seagreen4")
  }  else if (questionnaire_family=="without_cia") {
    questionnaire_colors <- c("EAT-26 (Eating Attitudes)" = "purple", "EDE-Q (Eating Disorder)" = "deeppink", "AAI (Appearance Anxiety)" = "brown2", 
                          "STAI-T (Trait Anxiety)" = "midnightblue", "BDI (Depression)" = "dodgerblue", 
                          "IOU (Intolerance of Uncertainty)" = "darkgoldenrod2", "OCI (Obsessive-Compulsive Inventory)" = "seagreen4")
  }



# Plot factor loadings
plot_factor_loadings <- ggplot(rtcors, aes(x = full_question, y = corr, fill = questionnaire)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0, color = "black") +
  scale_fill_manual(values = questionnaire_colors) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 8),  # Show full questions as rotated labels
    strip.background = element_blank(),
    strip.text = element_text(size = 14, face = "plain", hjust = 0),
    panel.grid.major.x = element_blank(),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  ) +
  labs(x = "Question", y = "Correlation", fill = "")

print(plot_factor_loadings)
# Save
ggsave(
  here::here("output", "correlations_with_remaining_time_not_ordered.pdf"), 
  plot = plot_factor_loadings,
  scale = 1,
  width = 25,
  height = 12,
  units = "in",
  dpi = 300
)


rtcors <- rtcors %>%
  arrange(corr) %>%
  mutate(full_question = factor(full_question, levels = full_question))


# Plot factor loadings
plot_factor_loadings <- ggplot(rtcors, aes(x = full_question, y = corr, fill = questionnaire)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0, color = "black") +
  scale_fill_manual(values = questionnaire_colors) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 8),  # Show full questions as rotated labels
    strip.background = element_blank(),
    strip.text = element_text(size = 14, face = "plain", hjust = 0),
    panel.grid.major.x = element_blank(),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  ) +
  labs(x = "Question", y = "Correlation", fill = "")

print(plot_factor_loadings)
# Save
ggsave(
  here::here("output", "correlations_with_remaining_time.pdf"), 
  plot = plot_factor_loadings,
  scale = 1,
  width = 25,
  height = 12,
  units = "in",
  dpi = 300
)

```

```{r}
library(dplyr)
library(kableExtra)
library(scales)
library(readr)

# Load the data
df <- rtcors

# Normalize correlation for coloring
df <- df %>%
  mutate(
    abs_corr = abs(corr),
    color = scales::col_numeric(
      palette = c("grey90", "purple"),
      domain = c(0, 1)
    )(abs_corr),
    corr_formatted = cell_spec(round(corr, 3), background = color, color = "white")
  )

# Create table
df %>%
  select(`Full Question` = full_question, Correlation = corr_formatted) %>%
  kable("html", escape = FALSE, align = c("l", "c")) %>%
  kable_styling(full_width = TRUE, position = "left", bootstrap_options = c("striped", "hover"))
```

### Look at official subscales


```{r fig.width=10}
sgr <-  read.csv(here::here("anon-data", "questionnaires", "subscales_and_single_items.csv"))

sgr2 <- sgr %>%
  group_by(questionnaire, Subscales) %>%
  group_by(questionnaire, Subscales) %>%
  summarise(corr = mean(corr), .groups = "drop") %>%
  arrange(desc(corr)) %>%
  mutate(Subscales = factor(Subscales, levels = unique(Subscales)))


#rtcors <- sgr %>%
#  arrange(corr) %>%
#  mutate(full_question = factor(full_question, levels = full_question))


# Plot factor loadings
plot_factor_loadings <- ggplot(sgr2, aes(x = Subscales, y = corr, fill = questionnaire)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0, color = "black") +
  scale_fill_manual(values = questionnaire_colors) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 8),  # Show full questions as rotated labels
    strip.background = element_blank(),
    strip.text = element_text(size = 14, face = "plain", hjust = 0),
    panel.grid.major.x = element_blank(),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  ) +
  labs(x = "Question", y = "Correlation", fill = "")

print(plot_factor_loadings)
# Save
ggsave(
  here::here("output", "correlations_with_remaining_time_by_subscale.pdf"), 
  plot = plot_factor_loadings,
  scale = 1,
  width = 12,
  height = 6,
  units = "in",
  dpi = 300
)



```
